[capabilities]
platform_name =
platform_version =
automation_name =
device_name =
app_path =
app_package =
app_activity =
appium_server =

[date]
logs_time_format = %%d/%%b/%%Y %%H:%%M:%%S %%A
files_time_format = %%d-%%b-%%Y %%H:%%M:%%S

[web]
url = https://freetv.tv/
browser = chrome

[general]
timeout = 5
; Choose web for browsers. iOS for iPhone/iPad. Android for Android phone/tablet
platform = web


[account]
; Add phone number, first and last name
phone_number =
first_name = Registration test
last_name = Automation


